// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: pre_go_crm_user_c.sql

package database

import (
	"context"
)

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT usr_email,
    usr_id
FROM pre_go_crm_user_c
WHERE usr_email = ?
LIMIT 1
`

type GetUserByEmailRow struct {
	UsrEmail string
	UsrID    uint32
}

func (q *Queries) GetUserByEmail(ctx context.Context, usrEmail string) (GetUserByEmailRow, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, usrEmail)
	var i GetUserByEmailRow
	err := row.Scan(&i.UsrEmail, &i.UsrID)
	return i, err
}

const updateUserStatusByID = `-- name: UpdateUserStatusByID :exec
UPDATE pre_go_crm_user_c
SET usr_status = $2,
    usr_updated_at = UNIX_TIMESTAMP()
WHERE usr_id = $1
`

func (q *Queries) UpdateUserStatusByID(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, updateUserStatusByID)
	return err
}
